version: '3.8'
services:
  ur-db:
    image: postgres
    environment:
      POSTGRES_USER: uradmin
      POSTGRES_PASSWORD: test77
      POSTGRES_DB: urdb
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod", "-U", "uradmin" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
  ur-scrapper:
    build: ./scrapper
    depends_on:
      ur-db:
        condition: service_healthy
    environment:
      UPLOAD_DATA: true
      DB_HOST: ur-db
      DB_USER: uradmin
      DB_PASSWORD: test77
      DB_NAME: urdb
  ur-service:
    build: ./service
    depends_on:
      ur-db:
        condition: service_healthy
    environment:
      DB_HOST: ur-db
      DB_USER: uradmin
      DB_PASSWORD: test77
      DB_NAME: urdb
    ports:
      - 8000:8000

